In [4]:
import pandas as pd
data = pd.read_csv('sars-cov-2.csv')

SyntaxError: invalid syntax (<ipython-input-4-62bcea099b25>, line 1)

In [5]:
data.tail()

NameError: name 'data' is not defined

In [29]:
data.describe()

             Length
count    170.000000
mean   18798.052941
std    14276.697417
min       87.000000
25%      400.750000
50%    29859.000000
75%    29882.000000
max    29945.000000

In [3]:
data.tail()

,Accession,Species,Genus,Family,Length,Authors,Publications,Host,BioSample,Sequence,CollectionDate,ReleaseDate,GeographicLocation,NucleotideStatus,GenBankTitle,IsolationSource,Country,InclusionDate
165,MN938384,Severe acute respiratory syndrome-related coro...,Betacoronavirus,"Entity[""Species"", ""Family:Coronaviridae""]",29838,"Chan,J.F.-W., Yuan,S., Kok,K.H., To,K.K.-W., C...","Missing[""NoInput""]","Entity[""Species"", ""Species:HomoSapiens""]",NaN,CAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACTTT...,"DateObject[{2020, 1, 10}, ""Day"", ""Gregorian"", ...","DateObject[{2020, 1, 24}, ""Day"", ""Gregorian"", ...","Entity[""Country"", ""China""]",complete,Severe acute respiratory syndrome coronavirus ...,oronasopharynx,"Entity[""Country"", ""China""]","DateObject[{2020, 1, 24}, ""Day"", ""Gregorian"", ..."
166,MN970004,Severe acute respiratory syndrome-related coro...,Betacoronavirus,"Entity[""Species"", ""Family:Coronaviridae""]",290,"Buathong,R., Wacharapluesadee,S., Lamsirithawo...","Missing[""NoInput""]","Entity[""Species"", ""Species:HomoSapiens""]",NaN,TAAACACCTCATACCACTTATGTACAAAGGACTTCCTTGGAATGTA...,"DateObject[{2020, 1, 13}, ""Day"", ""Gregorian"", ...","DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Entity[""Country"", ""Thailand""]",NaN,Severe acute respiratory syndrome coronavirus ...,"lung, oronasopharynx","Entity[""Country"", ""Thailand""]","DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ..."
167,MN970003,Severe acute respiratory syndrome-related coro...,Betacoronavirus,"Entity[""Species"", ""Family:Coronaviridae""]",290,"Buathong,R., Wacharapluesadee,S., Lamsirithawo...","Missing[""NoInput""]","Entity[""Species"", ""Species:HomoSapiens""]",NaN,TAAACACCTCATACCACTTATGTACAAAGGACTTCCTTGGAATGTA...,"DateObject[{2020, 1, 8}, ""Day"", ""Gregorian"", -5.]","DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ...","Entity[""Country"", ""Thailand""]",NaN,Severe acute respiratory syndrome coronavirus ...,"lung, oronasopharynx","Entity[""Country"", ""Thailand""]","DateObject[{2020, 1, 23}, ""Day"", ""Gregorian"", ..."
168,NC_045512,Severe acute respiratory syndrome-related coro...,Betacoronavirus,"Entity[""Species"", ""Family:Coronaviridae""]",29903,"Wu,F., Zhao,S., Yu,B., Chen,Y.-M., Wang,W., Hu...","Missing[""NoInput""]","Entity[""Species"", ""Species:HomoSapiens""]",NaN,ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...,"DateObject[{2019, 12}, ""Month"", ""Gregorian"", -5.]","DateObject[{2020, 1, 13}, ""Day"", ""Gregorian"", ...","Entity[""Country"", ""China""]","refseq, complete",Severe acute respiratory syndrome coronavirus ...,NaN,"Entity[""Country"", ""China""]","DateObject[{2020, 1, 13}, ""Day"", ""Gregorian"", ..."
169,MN908947,Severe acute respiratory syndrome-related coro...,Betacoronavirus,"Entity[""Species"", ""Family:Coronaviridae""]",29903,"Wu,F., Zhao,S., Yu,B., Chen,Y.M., Wang,W., Son...","Hyperlink[32015508, ""https://www.ncbi.nlm.nih....","Entity[""Species"", ""Species:HomoSapiens""]",NaN,ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGA...,"DateObject[{2019, 12}, ""Month"", ""Gregorian"", -5.]","DateObject[{2020, 1, 12}, ""Day"", ""Gregorian"", ...","Entity[""Country"", ""China""]",complete,Severe acute respiratory syndrome coronavirus ...,NaN,"Entity[""Country"", ""China""]","DateObject[{2020, 1, 12}, ""Day"", ""Gregorian"", ..."

In [15]:
# This is the mapping of Amino Acids to Proteins. 3 Amino Acids, denoted by the letter they start with, form a codon, which encodes a Proteins
def translate(seq): 
       
    table = { 
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M', 
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T', 
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K', 
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',                  
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L', 
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P', 
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q', 
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R', 
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V', 
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A', 
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E', 
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G', 
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S', 
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L', 
        'TAC':'Y', 'TAT':'Y', 'TAA':'_', 'TAG':'_', 
        'TGC':'C', 'TGT':'C', 'TGA':'_', 'TGG':'W', 
    } 
    protein ="" 
    if len(seq)%3 == 0: 
        print("here")
        for i in range(0, len(seq), 3): 
            codon = seq[i:i + 3] 
            protein += table[codon]
    return protein

In [ ]:
# Get the sequence of amino acids from the data set

In [14]:
output = translate("TTTTGTGCC")
print(output)

here
FCA